// TODO: EF Core Migration - Initial Schema
// This migration will be generated by EF Core when you run:
// dotnet ef migrations add InitialSchema --project src/domain --startup-project src/api
//
// Example structure:
// public partial class InitialSchema : Migration
// {
//     protected override void Up(MigrationBuilder migrationBuilder)
//     {
//         migrationBuilder.CreateTable(
//             name: "domains",
//             columns: table => new
//             {
//                 Id = table.Column<Guid>(type: "uuid", nullable: false),
//                 Name = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
//                 Enabled = table.Column<bool>(type: "boolean", nullable: false),
//                 IntervalMinutes = table.Column<int>(type: "integer", nullable: false),
//                 CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
//                 UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
//             },
//             constraints: table =>
//             {
//                 table.PrimaryKey("PK_domains", x => x.Id);
//             });
//
//         // ... other tables
//     }
//
//     protected override void Down(MigrationBuilder migrationBuilder)
//     {
//         migrationBuilder.DropTable(name: "domains");
//         // ... drop other tables
//     }
// }
